name: Build and release Python packages - Linux
on: workflow_dispatch

jobs:
  build:
    runs-on: ['ubuntu-latest']
    container:
      image: quay.io/pypa/manylinux_2_28_x86_64

    steps:
      - name: Checkout fast-colorthief
        run: |
          cd /
          mkdir fast_colorthief
          cd fast_colorthief/
          git clone https://github.com/bedapisl/fast-colorthief
          cd fast-colorthief/
          git submodule update --init --recursive
      - name: List available Python versions
        run: 
          ls /opt/python
      - name: Build wheels
        run: |
          cd /fast_colorthief/fast-colorthief/
          /opt/python/cp36-cp36m/bin/python setup.py bdist_wheel
          /opt/python/cp37-cp37m/bin/python setup.py bdist_wheel
          /opt/python/cp38-cp38/bin/python setup.py bdist_wheel
          /opt/python/cp39-cp39/bin/python setup.py bdist_wheel
          /opt/python/cp310-cp310/bin/python setup.py bdist_wheel
          /opt/python/cp311-cp311/bin/python setup.py bdist_wheel
          /opt/python/cp312-cp312/bin/python setup.py bdist_wheel
      - name: Auditwheel & publish
        run: |
          cd /fast_colorthief/fast-colorthief/
          /opt/python/cp39-cp39/bin/pip install auditwheel twine
          auditwheel repair dist/*
          /opt/python/cp39-cp39/bin/python -m twine upload -u __token__  -p ${{ secrets.PYPI_UPLOAD_TOKEN }} wheelhouse/*
